---
#
- hosts: all
  become: yes

  vars:
    configure_pihole: true


  vars_files:
    - group_vars/password_vault.yml


  tasks:
    - include_role:
        name: ansible-pihole-heise
      vars:
        timezone: Europe/Vienna
        stubby_image: "juharov/stubby-vance-arm:latest"
        REV_SERVER_DOMAIN: "fritz.box"

